name: Test Actions
on:
  push:

jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Source
        uses: actions/checkout@v1
      - name: Set the test var
        uses: ./
      - name: Print the test var
        run: echo ${{ steps.private-action.outputs.test-var }}
