name: Test Action
on:
  push:

jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set the test var
        uses: ./
        with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
      -name: Print the test var
        run: echo ${{ steps.private-action.outputs.test-var }}
